### ISSUE TITLE
dont mind this issue

### ISSUE THREAD

**Issue by Mercotui** [derpicated/articated#1]
just a test

**Comment by idelsink** [comment]
A test for what?

**Comment by Mercotui** [comment]
i couldnt see articated in my list of "projects i contribute to" so i made an issue to "contribute", its a hack, but it works

**Comment by idelsink** [comment]
lol

**Comment by idelsink** [comment]
woops

**Comment by Mercotui** [comment]
4 emails from a test issue, gj

>mute thread
