### ISSUE TITLE
Use of undeclared identifier 'GL_R8' / 'GL_RED'

### ISSUE THREAD

**Issue by idelsink** [derpicated/articated#21]
When building the android application, initialized using the following CMake arguments, I get the `use of undeclared identifier 'GL_R8/GL_RED'` errors.

```
cmake .. \
-DCMAKE_TOOLCHAIN_FILE=/home/ingmar/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake \
-DANDROID=ON \
-DQt5_DIR=/home/ingmar/Qt/5.10.1/android_armv7/lib/cmake/Qt5 \
-DQT_ANDROID_SDK_ROOT=/home/ingmar/Android/Sdk \
-DQT_ANDROID_ANT=/usr/bin/ant \
-DANDROID_NDK=/home/ingmar/Android/Sdk/ndk-bundle \
-DJAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b13-0.fc29.x86_64
```

```
/home/ingmar/workspace/articated/source/augmentation_widget/augmentation_widget.cpp:114:33: error: 
      use of undeclared identifier 'GL_R8'
            internalformat_gl = GL_R8;
                                ^
/home/ingmar/workspace/articated/source/augmentation_widget/augmentation_widget.cpp:115:33: error: 
      use of undeclared identifier 'GL_RED'
            format_gl         = GL_RED;
                                ^
2 errors generated.
make[2]: *** [source/augmentation_widget/CMakeFiles/augmentation.dir/build.make:79: source/augmentation_widget/CMakeFiles/augmentation.dir/augmentation_widget.cpp.o] Error 1      
make[1]: *** [CMakeFiles/Makefile2:241: source/augmentation_widget/CMakeFiles/augmentation.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by idelsink** [comment]
We're using `GLESv3` and this should be available?

**Comment by idelsink** [comment]
I'm on cb0be3c (Currently head of https://github.com/derpicated/articated/tree/fix/android)

**Comment by Mercotui** [comment]
I don't understand how we are getting this issue, I'm going to have to replicate it locally to fully investigate.

As you mentioned, the [OpenGL-ES 3.0 spec](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml) lists GL_R8 as a valid sized internal format, with GL_RED being the accompanying format.

**Comment by idelsink** [comment]
When I include the `QOpenGLTexture` file in the `augmentation_widget.cpp` file. And replace `GL_R8` with `QOpenGLTexture::R8_UNorm` and `GL_RED` with `QOpenGLTexture::Red` it all build fine. (It fails with linking but that is due to another issue, see https://github.com/derpicated/articated/issues/22)

**Comment by Mercotui** [comment]
That sounds like a hotfix, as we are not using QOpenGLTextures but rather native OpenGL texture handles, and the code should work without including it.

**Comment by idelsink** [comment]
Yes, that is a hotfix, not the solution.

**Comment by Mercotui** [comment]
Interesting detail that can be found in the last paragraphs of [this QT blogpost](https://blog.qt.io/blog/2015/09/09/cross-platform-opengl-es-3-apps-with-qt-5-6/), it seems like QT is not always succesfull in detecting the `GLES/gl3.h`, the file where `GL_RED` is defined.
If this happens, it defaults to GLES 2.0, which does not have support for `GL_RED`, leading to the behaviour described in this issue.

I have implemented a preprocessor switch to include `GLES/gl3.h` in the case of an android build, see commit 6dc4bfbcb301cb9af25eb947b5cfceadf365e83e
Closing the issue
