### ISSUE TITLE
set CMake ANDROID variable default to off

### ISSUE THREAD

**Issue by idelsink** [derpicated/articated#4]
Make it easier to build for desktop and set the `ANDROID` CMake variable default to off. 
So the user only has to do the following for a desktop build:
```sh
mkdir build && cd build
cmake .. \
-DQt5_DIR=/home/user/Qt/5.7/gcc_64/lib/cmake/Qt5
```

**Comment by Mercotui** [comment]
hhm I wanted to yell at you for creating such a trivial enhancement request. But now I see the issue, that the variable is set in the submodule `qt-android-cmake`. So we could fork it, or include it into the repo, and fix it that way... although I.M.O. it would be nicer to overwrite it the variable somewhere else and leave the submodule as is.., looking into that atm, will report back

**Comment by Mercotui** [comment]
ok, actually, it was a single word in the root cmakelist... I'm proud of your laziness XD
fixed in d2d09f6ed2984384e336ee9fe6f1f2821459532d

**Comment by idelsink** [comment]
thank you my dear friend but I'd just like to interject for moment. What you're referring to as this issue, is in fact, a GNU/Issue, or as I've recently taken to calling it, GNU plus issue. The issue is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called issue, and many of its issues are not aware that it is basically the GNU system, developed by the GNU Project.

There really is an issue, and these people are causing it, but it is just a part of the system they use. The issue is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an issue system, but useless by itself; it can only function in the context of a complete operating system. The issue is normally used in combination with the GNU operating system: the whole system is basically GNU with issues added, or GNU/issues. All the so-called issue distributions are really distributions of GNU/issues!

**Comment by Mercotui** [comment]
thanks Richard Stallmar
