### ISSUE TITLE
expand readme

### ISSUE THREAD

**Issue by Mercotui** [derpicated/articated#5]
the repo readme currently does not explain the applications features or workings.
It could use some fixing and expanding.

**Comment by Mercotui** [comment]
Took a shot at this in 8dc69cd9a741a21238a79aa93daae8b19674f054.
@idelsink could you check my changes, and give me your feedback?

**Comment by Mercotui** [comment]
whooops

**Comment by idelsink** [comment]
From what I read, I can say that it's fine for now. 
Perhaps add Android 6 to the list of tested devices? My phone is running Android 6.0.1 at the moment.

But I think this can be closed than.
